copyright: Copyright &copy; 2023 Mirascope, Inc.
site_name: Mirascope
site_url: https://docs.mirascope.io/
site_description: Mirascope is an open-source library for the most pythonic LLM application building experience.
repo_name: mirascope
repo_url: https://github.com/Mirascope/mirascope/
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotation
    - content.code.copy
    - content.code.link
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mirascope
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WilliamBakst
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wbakst/
  analytics:
    provider: google
    property: G-DJHT1QG9GK

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - mike:
      alias_type: symlink
      canonical_version: latest
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false
            docstring_style: google

nav:
  - Get Started:
      - Mirascope: "README.md"
      - Contributing: "CONTRIBUTING.md"
      - How to help: "HELP.md"
  - Concepts:
      - Pydantic Prompts: "concepts/pydantic_prompts.md"
      - LLM Convenience Wrappers: "concepts/llm_convenience_wrappers.md"
      - Mirascope CLI: "concepts/mirascope_cli.md"
  - Cookbook:
      - SQuAD Extraction: "cookbook/squad_extraction.md"
      - RAG: "cookbook/rag.md"
      - Integrating LangSmith with Mirascope: "cookbook/langsmith.md"
  - API Reference:
      - chat:
          - "api/chat/index.md"
          - openai:
              - "api/chat/openai/index.md"
              - models:
                  - "api/chat/openai/models/index.md"
                  - OpenAIChat: "api/chat/openai/models/openai_chat.md"
                  - AsyncOpenAIChat: "api/chat/openai/models/openai_chat_async.md"
              - parsers:
                  - "api/chat/openai/parsers/index.md"
                  - OpenAIParser: "api/chat/openai/parsers/openai_tool_stream_parser.md"
                  - AsyncOpenAIParser: "api/chat/openai/parsers/openai_tool_stream_parser_async.md"
              - tools: "api/chat/openai/tools.md"
              - types: "api/chat/openai/types.md"
              - utils: "api/chat/openai/utils.md"
      - cli:
          - "api/cli/index.md"
          - commands: "api/cli/commands.md"
          - constants: "api/cli/constants.md"
          - generic: "api/cli/generic.md"
          - schemas: "api/cli/schemas.md"
          - utils: "api/cli/utils.md"
      - enums: "api/enums.md"
      - prompts:
          - "api/prompts/index.md"
          - messages: "api/prompts/messages.md"
          - prompt: "api/prompts/prompt.md"
          - tools: "api/prompts/tools.md"
