copyright: Copyright &copy; 2023 Mirascope, Inc.
site_name: Mirascope
site_url: https://docs.mirascope.io/
site_description: Mirascope is an intuitive approach to building with LLMs.
repo_name: mirascope
repo_url: https://github.com/Mirascope/mirascope/
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotation
    - content.code.copy
    - content.code.link
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mirascope
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WilliamBakst
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wbakst/
  analytics:
    provider: google
    property: G-DJHT1QG9GK

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - mike:
      alias_type: symlink
      canonical_version: latest
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false
            docstring_style: google

nav:
  - Get Started:
      - "index.md"
      - Philosophy: "PHILOSOPHY.md"
      - Supported Providers: "SUPPORTED_PROVIDERS.md"
  - Learn:
      - Prompts: "learn/prompts.md"
      - Calls: "learn/calls.md"
      - Streams: "learn/streams.md"
      - Response Models: "learn/response_models.md"
      - Tools (Function Calling): "learn/tools_(function_calling).md"
  - Cookbook:
      - "cookbook/index.md"
      - Prompt Engineering:
          - "cookbook/prompt_engineering/index.md"
          - Text-Based:
              - "cookbook/prompt_engineering/text_based/index.md"
              - Self-Ask: "cookbook/prompt_engineering/text_based/self_ask.md"
          - Chaining:
              - "cookbook/prompt_engineering/chaining/index.md"
      - Text Classification: "cookbook/text_classification.md"
      - LLM Validation With Retries: "cookbook/llm_validation_with_retries.md"
      - Agents:
          - "cookbook/agents/index.md"
          - Blog Writing Agent: "cookbook/agents/blog_writing_agent.md"
  - Integrations:
      - "integrations/index.md"
      - "integrations/tenacity.md"
      - "integrations/custom_middleware.md"
      - "integrations/logfire.md"
      - "integrations/langfuse.md"
      - OpenTelemetry:
          - "integrations/opentelemetry/index.md"
          - "integrations/opentelemetry/hyperdx.md"
  - API Reference:
      - "api/index.md"
      - core:
          - "api/core/index.md"
          - anthropic:
              - "api/core/anthropic/index.md"
              - call_params: "api/core/anthropic/call_params.md"
              - call_response_chunk: "api/core/anthropic/call_response_chunk.md"
              - call_response: "api/core/anthropic/call_response.md"
              - call: "api/core/anthropic/call.md"
              - dynamic_config: "api/core/anthropic/dynamic_config.md"
              - stream: "api/core/anthropic/stream.md"
              - tool: "api/core/anthropic/tool.md"
          - base:
              - "api/core/base/index.md"
              - call_factory: "api/core/base/call_factory.md"
              - call_params: "api/core/base/call_params.md"
              - call_response_chunk: "api/core/base/call_response_chunk.md"
              - call_response: "api/core/base/call_response.md"
              - dynamic_config: "api/core/base/dynamic_config.md"
              - message_param: "api/core/base/message_param.md"
              - metadata: "api/core/base/metadata.md"
              - prompt: "api/core/base/prompt.md"
              - tool: "api/core/base/tool.md"
              - toolkit: "api/core/base/toolkit.md"
          - cohere:
              - "api/core/cohere/index.md"
              - call_params: "api/core/cohere/call_params.md"
              - call_response_chunk: "api/core/cohere/call_response_chunk.md"
              - call_response: "api/core/cohere/call_response.md"
              - call: "api/core/cohere/call.md"
              - dynamic_config: "api/core/cohere/dynamic_config.md"
              - stream: "api/core/cohere/stream.md"
              - tool: "api/core/cohere/tool.md"
          - gemini:
              - "api/core/gemini/index.md"
              - call_params: "api/core/gemini/call_params.md"
              - call_response_chunk: "api/core/gemini/call_response_chunk.md"
              - call_response: "api/core/gemini/call_response.md"
              - call: "api/core/gemini/call.md"
              - dynamic_config: "api/core/gemini/dynamic_config.md"
              - stream: "api/core/gemini/stream.md"
              - tool: "api/core/gemini/tool.md"
          - groq:
              - "api/core/groq/index.md"
              - call_params: "api/core/groq/call_params.md"
              - call_response_chunk: "api/core/groq/call_response_chunk.md"
              - call_response: "api/core/groq/call_response.md"
              - call: "api/core/groq/call.md"
              - dynamic_config: "api/core/groq/dynamic_config.md"
              - stream: "api/core/groq/stream.md"
              - tool: "api/core/groq/tool.md"
          - litellm:
              - "api/core/litellm/index.md"
              - call: "api/core/litellm/call.md"
          - mistral:
              - "api/core/mistral/index.md"
              - call_params: "api/core/mistral/call_params.md"
              - call_response_chunk: "api/core/mistral/call_response_chunk.md"
              - call_response: "api/core/mistral/call_response.md"
              - call: "api/core/mistral/call.md"
              - dynamic_config: "api/core/mistral/dynamic_config.md"
              - stream: "api/core/mistral/stream.md"
              - tool: "api/core/mistral/tool.md"
          - openai:
              - "api/core/openai/index.md"
              - call_params: "api/core/openai/call_params.md"
              - call_response_chunk: "api/core/openai/call_response_chunk.md"
              - call_response: "api/core/openai/call_response.md"
              - call: "api/core/openai/call.md"
              - dynamic_config: "api/core/openai/dynamic_config.md"
              - stream: "api/core/openai/stream.md"
              - tool: "api/core/openai/tool.md"
      - integrations:
          - "api/integrations/index.md"
          - langfuse: "api/integrations/langfuse.md"
          - logfire: "api/integrations/logfire.md"
          - otel: "api/integrations/otel.md"
          - tenacity: "api/integrations/tenacity.md"
  - Help: "HELP.md"
  - Contributing: "CONTRIBUTING.md"
