[tool.poetry]
name = "mirascope"
version = "1.0.0"
description = "NEEDS DESCRIPTION"
license = "MIT"
authors = [
    "William Bakst <william@mirascope.io>",
    "Brendan Kao <brendan@mirascope.io>",
]
readme = "docs/README.md"
packages = [{ include = "mirascope" }]
repository = "https://github.com/Mirascope/mirascope"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pydantic = "^2.7.4"
jiter = "^0.4.2"
docstring-parser = ">=0.15,<1.0"
eval-type-backport = "^0.2.0"

# A list of optional dependencies that are required for certain features
openai = { version = "^1.6.0", optional = true }

[tool.poetry.extras]
openai = ["openai"]
all = ["openai"]

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pyright = "^1.1.368"
ruff = "^0.4.9"
pytest-asyncio = "^0.23.7"
pytest-cov = "^4.1.0"

[tool.poetry.group.docs.dependencies]
mike = "^2.0.0"
mkdocs = "^1.4.3"
mkdocs-material = "^9.1.18"
mkdocstrings = "^0.22.0"
mkdocstrings-python = "^1.1.2"

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
line-length = 88
target-version = "py39"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
