blank_issues_enabled: true
contact_links:
  - name: 💬 Join Slack
    url: "https://docs.mirascope.io/HELP/#slack"
    about: Join the Mirascope Slack to ask questions, get help and chat about Mirascope
