wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1709066356.183629
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.16.3
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
